call plug#begin()
Plug 'junegunn/fzf', {'dir': '~/.fzf'}
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-surround'
Plug 'easymotion/vim-easymotion'
Plug 'rstacruz/sparkup'
Plug 'airblade/vim-gitgutter'
Plug 'sheerun/vim-polyglot'
call plug#end()

colorscheme smyck

set nocompatible
syntax enable
filetype plugin indent on


" Mappings
let mapleader=","

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
noremap h <NOP>
" noremap j <NOP>
" noremap k <NOP>
noremap l <NOP>

nnoremap <space> /
nnoremap <enter> :
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>
inoremap jk <Esc>
" inoremap <enter> <Esc>
" nnoremap <enter> i<enter>
noremap <c-t> <c-]>

map q <Plug>(easymotion-prefix)
noremap <leader>p :Files<enter>
noremap <leader>l :Buffers<enter>
noremap <leader>m :w<enter>


" Options
set backspace=2
let g:loaded_matchparen=1
set relativenumber
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set autoread
set ignorecase
set incsearch 
set hidden
set nobackup
set nowb
set noswapfile
