call plug#begin()
Plug 'sheerun/vim-polyglot'
Plug 'airblade/vim-gitgutter'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-surround'
call plug#end()

syntax enable
filetype plugin indent on
colorscheme smyck

set nocompatible

set path+=**
set wildmenu
set ignorecase smartcase
set incsearch

set iskeyword+=-

set nowrap
set tabstop=2 shiftwidth=2 softtabstop=2
set expandtab
let g:loaded_matchparen=1

set autoread
set hidden
set nobackup
set nowb
set noswapfile
set laststatus=2

set rtp+=~/.fzf
set grepprg=ag\ --nogroup\ --nocolor

command Bd bp|bd #

nnoremap K :FZF<cr>
nnoremap s :w<cr>
nnoremap h :bnext<cr>
nnoremap l :bnext<cr>
nnoremap <Tab> <C-w>w
nnoremap <S-Tab> <C-w>W
nnoremap <space> :

inoremap <C-e> <></><Esc>5hdiwp3lpT>i

