autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
bindkey '^[[Z' reverse-menu-complete

PROMPT='%1~ '

export VISUAL=nvim
export EDITOR=nvim

alias e="$EDITOR"
alias l="clear && ls -alG"
alias s="git status"
alias rmds="find . -name '.DS_Store' -type f -delete"
