autoload -Uz compinit && compinit
zstyle ':completion:*' menu select

PROMPT='%1~ '

export VISUAL=nvim
export EDITOR=nvim
export FZF_DEFAULT_COMMAND='ag -g ""'

alias e="$EDITOR"
alias l="clear && ls -alG"
alias s="git status"
alias rmds="find . -name '.DS_Store' -type f -delete"